import { GridColDef, GridRowsProp } from '@mui/x-data-grid';
import {
    renderDocCell,
    renderStudentCell,
    renderSupervisorCell,
    renderTopicCell,
    renderTopicStatusCell,
} from '../../lib';

export const rows: GridRowsProp = [
    {
        id: 1,
        student: { id: 101, name: 'Иванов Иван Петрович' },
        group: 'РИ-410940',
        topic: { id: 't1', name: 'Разработка клиентской части платформы учебной' },
        status: 'Утверждена',
        role: 'Frontend-разработчик',
        supervisor: { id: 's1', name: 'Сидоров Михаил Иванович' },
        doc1: true,
    },
    {
        id: 2,
        student: { id: 102, name: 'Петров Сергей Владимирович' },
        group: 'РИ-410940',
        topic: { id: 't2', name: 'Разработка backend-части корпоративного портала' },
        status: 'На рассмотрении',
        role: 'Backend-разработчик',
        supervisor: { id: 's2', name: 'Кузнецов Александр Олегович' },
        companyName: 'ООО "ТехноСофт"',
        companySupervisor: 'Андреев Василий Николаевич',
        doc1: false,
    },
    {
        id: 3,
        student: { id: 103, name: 'Смирнова Анастасия Олеговна' },
        group: 'РИ-410940',
        topic: { id: 't3', name: 'Проектирование базы данных для CRM-системы' },
        status: 'Отклонена',
        role: 'Data Engineer',
        supervisor: { id: 's3', name: 'Григорьев Дмитрий Петрович' },
        companyName: 'АО "ИнфоТех"',
        companySupervisor: 'Не указано',
    },
    {
        id: 4,
        student: { id: 104, name: 'Васильев Алексей Дмитриевич' },
        group: 'РИ-410940',
        topic: { id: 't4', name: 'Разработка мобильного приложения для доставки еды' },
        status: 'Утверждена',
        role: 'Mobile-разработчик',
        supervisor: { id: 's4', name: 'Романов Евгений Викторович' },
        companyName: 'ООО "FoodExpress"',
        companySupervisor: 'Фёдоров Николай Сергеевич',
        doc1: true,
    },
    {
        id: 5,
        student: { id: 105, name: 'Козлова Марина Викторовна' },
        group: 'РИ-410940',
        topic: { id: 't5', name: 'Разработка системы машинного обучения для рекомендаций' },
        status: 'На рассмотрении',
        role: 'ML Engineer',
        supervisor: { id: 's5', name: 'Никитин Олег Анатольевич' },
        doc1: true,
    },
    {
        id: 6,
        student: { id: 106, name: 'Фролов Дмитрий Сергеевич' },
        group: 'РИ-410941',
        topic: { id: 't6', name: 'Разработка бэкенда для IoT-устройств' },
        status: 'Утверждена',
        role: 'Backend-разработчик',
        supervisor: { id: 's6', name: 'Гаврилов Виктор Степанович' },
        companyName: 'АО "СмартТех"',
        companySupervisor: 'Зиновьев Андрей Павлович',
        doc1: false,
    },
    {
        id: 7,
        student: { id: 107, name: 'Морозова Наталья Евгеньевна' },
        group: 'РИ-410941',
        topic: { id: 't7', name: 'Разработка системы автоматического тестирования' },
        status: 'Отклонена',
        role: 'QA Engineer',
        supervisor: { id: 's7', name: 'Рыбаков Сергей Владимирович' },
    },
    {
        id: 8,
        student: { id: 108, name: 'Гусев Артём Александрович' },
        group: 'РИ-410941',
        topic: { id: 't8', name: 'Создание веб-приложения для управления проектами' },
        status: 'На рассмотрении',
        role: 'Fullstack-разработчик',
        supervisor: { id: 's8', name: 'Беляев Алексей Константинович' },
        companyName: 'ООО "DevSoft"',
        companySupervisor: 'Мельников Дмитрий Олегович',
    },
    {
        id: 9,
        student: { id: 109, name: 'Романова Екатерина Павловна' },
        group: 'РИ-410941',
        topic: { id: 't9', name: 'Разработка нейросетевой модели для анализа текстов' },
        status: 'Утверждена',
        role: 'ML Engineer',
        supervisor: { id: 's9', name: 'Тихонов Олег Владиславович' },
        companyName: 'АО "AI Solutions"',
        doc1: true,
    },
    {
        id: 10,
        student: { id: 110, name: 'Кузнецов Артём Юрьевич' },
        group: 'РИ-410941',
        topic: { id: 't10', name: 'Разработка админ-панели для управления контентом' },
        status: 'Отклонена',
        role: 'Fullstack-разработчик',
        supervisor: { id: 's10', name: 'Орлов Николай Викторович' },
        companyName: 'ООО "WebTech"',
        companySupervisor: 'Иванов Дмитрий Сергеевич',
    },
];

const first = [
    'mark', // Оценка
    'topicName', // Тема
    'result', // Статус(прошел/нет)
    'comment,', // Комментарий эксперта
];

export const columns: GridColDef[] = [
    { field: 'id', headerName: '№', width: 50, align: 'center' },
    { field: 'student', headerName: 'ФИО', width: 300, sortable: false, renderCell: renderStudentCell },
    { field: 'group', headerName: 'Группа', width: 110 },
    { field: 'topic', headerName: 'Тема', width: 400, sortable: false, renderCell: renderTopicCell },
    { field: 'status', headerName: 'Статус темы', width: 180, renderCell: renderTopicStatusCell },
    { field: 'role', headerName: 'Роль', width: 200 },
    { field: 'supervisor', headerName: 'Руководитель', width: 300, renderCell: renderSupervisorCell, sortable: false },
    { field: 'companyName', headerName: 'Предприятие', width: 300, sortable: false },
    { field: 'companySupervisor', headerName: 'Куратор от предприятия', width: 300, sortable: false },
    { field: 'doc1', headerName: 'Задание', width: 85, sortable: false, renderCell: renderDocCell },
];
